# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15kGFP6v5VTCiMEuuL8622xx3CJRuH-KX
"""

# Cell 1: Imports
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from pathlib import Path

# Cell 2: Load dataset
dataset_path = Path("insurance.csv")
df = pd.read_csv(dataset_path)
df.head()

# Cell 3: Basic info
print("Shape:", df.shape)
print("Columns:", df.columns.tolist())
df.describe()

# Cell 4: Histogram of Age
plt.figure(figsize=(7,4))
sns.histplot(df['age'], bins=20, kde=True)
plt.title("Distribution of Age")
plt.show()

# Cell 5: Boxplot of numeric features
sns.boxplot(data=df[['age','bmi','children','charges']])
plt.title("Boxplot of Numeric Features")
plt.show()

# Cell 6: KDE Plots
for col in ['age','bmi','children']:
    sns.kdeplot(df[col], fill=True)
    plt.title(f"KDE of {col}")
    plt.show()

# Cell 8: Violin plot BMI by smoker
sns.violinplot(x='smoker', y='bmi', data=df, inner='box')
plt.title("BMI by Smoker")
plt.show()

# Cell 9: Pairplot
sns.pairplot(df[['age','bmi','children','charges']], diag_kind='kde')
plt.show()